#!/bin/zsh

# Путь к LibreOffice
LIBREOFFICE_PATH="/Applications/LibreOffice.app/Contents/MacOS/soffice"
TEMP_DIR="/private/tmp"
TEMPLATE_PATH="./avenir.ott"

# Проверка зависимостей: LibreOffice, qpdf и exiftool
check_dependencies() {
    echo "Проверка LibreOffice..."
    if [ ! -x "$LIBREOFFICE_PATH" ]; then
        echo "Ошибка: LibreOffice не найден. Убедитесь, что оно установлено."
        exit 1
    fi

    echo "Проверка qpdf..."
    if ! command -v qpdf &>/dev/null; then
        echo "qpdf не найден. Устанавливаю через Homebrew..."
        brew install qpdf || {
            echo "Ошибка: Не удалось установить qpdf. Установите его вручную и попробуйте снова."
            exit 1
        }
    fi

    echo "Проверка exiftool..."
    if ! command -v exiftool &>/dev/null; then
        echo "exiftool не найден. Устанавливаю через Homebrew..."
        brew install exiftool || {
            echo "Ошибка: Не удалось установить exiftool. Установите его вручную и попробуйте снова."
            exit 1
        }
    fi
}

# Конвертация DOCX в PDF через LibreOffice
convert_docx_to_pdf() {
    INPUT_FILE=$1
    OUTPUT_FILE=$2

    TEMP_ODT="$TEMP_DIR/$(basename "${INPUT_FILE%.docx}.odt")"
    TEMP_TEMPLATE="$TEMP_DIR/$(basename "$TEMPLATE_PATH")"

    echo "Копирование шаблона $TEMPLATE_PATH в $TEMP_TEMPLATE..."
    cp "$TEMPLATE_PATH" "$TEMP_TEMPLATE" || {
        echo "Ошибка: Не удалось скопировать шаблон в временную директорию."
        exit 1
    }

    echo "Конвертация $INPUT_FILE в ODT..."
    "$LIBREOFFICE_PATH" --headless --convert-to odt --outdir "$TEMP_DIR" "$INPUT_FILE" || {
        echo "Ошибка: LibreOffice не смог конвертировать $INPUT_FILE в ODT."
        exit 1
    }

    if [ ! -f "$TEMP_ODT" ]; then
        echo "Ошибка: ODT файл $TEMP_ODT не найден."
        exit 1
    fi

    echo "ODT успешно создан: $TEMP_ODT"

    echo "Применение шаблона и конвертация в PDF..."
    "$LIBREOFFICE_PATH" --headless --convert-to pdf:writer_pdf_Export --outdir "$(dirname "$OUTPUT_FILE")" "$TEMP_ODT" || {
        echo "Ошибка: LibreOffice не смог конвертировать $TEMP_ODT в PDF."
        exit 1
    }

    FINAL_PDF="$(dirname "$OUTPUT_FILE")/$(basename "${INPUT_FILE%.docx}.pdf")"
    if [ -f "$FINAL_PDF" ]; then
        mv "$FINAL_PDF" "$OUTPUT_FILE"
        echo "PDF успешно создан: $OUTPUT_FILE"
    else
        echo "Ошибка: PDF файл не найден."
        exit 1
    fi

    rm -f "$TEMP_ODT" "$TEMP_TEMPLATE"
}

# Добавление метаданных через exiftool
update_metadata_with_exiftool() {
    PDF_FILE=$1

    echo "Добавление метаданных через exiftool..."
    exiftool -overwrite_original \
        -Title="CV Document" \
        -Author="Iakov Senatov" \
        -Keywords="CV, PDF, Iakov Senatov" \
        -Description="Generated CV Document for Iakov Senatov" \
        -Subject="OS: $(uname -a); Processor: $(sysctl -n machdep.cpu.brand_string); Generated by docx2pdf.sh script; User: $USER" \
        -BaseURL="https://github.com/senatov/MiMiNavigator" \
        "$PDF_FILE" || {
        echo "Ошибка: Не удалось обновить метаданные через exiftool."
        return 1
    }

    echo "Метаданные успешно обновлены: $PDF_FILE"
}



# Проверка аргументов
if [ "$#" -ne 2 ]; then
    echo "Использование: $0 input.docx output.pdf"
    exit 1
fi

INPUT_FILE=$1
OUTPUT_FILE=$2

check_dependencies

convert_docx_to_pdf "$INPUT_FILE" "$OUTPUT_FILE"

echo "Шаг 1 завершён: PDF создан."

update_metadata_with_exiftool "$OUTPUT_FILE"

echo "Шаг 2 завершён: PDF с метаданными готов. Файл: $OUTPUT_FILE"